/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.parking;

import db.KoneksiMysql;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nezae
 */
public class Konfigurasi extends javax.swing.JFrame {
    
    Connection Con;
    Statement stm;
    ResultSet RsKonfigurasi;
    private String tempUsername = "";
    /**
     * Creates new form Konfigurasi
     */
    public Konfigurasi() {
        initComponents();
        open_db();
        data_jenis_kendaraan();
        baca_data_users();
        data_kapasitas();
    }
    
    private void open_db(){
        try {
            KoneksiMysql konek = new KoneksiMysql();
            Con = konek.getConnection();
            stm = Con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            System.out.println("Berhasil ");
        } catch (Exception e) {
            System.out.println("Error : " + e);
        }
    }
    
    void baca_data_users() {
        try {
            ResultSet users = stm.executeQuery("select * from users");
            ResultSetMetaData meta = users.getMetaData();
            int col = meta.getColumnCount();
            Integer baris = 0;
            
            while (users.next()) {
                baris = users.getRow();
            }
            Object[][] dataTable = new Object[baris][col];
            int x = 0;
            users.beforeFirst();
            
            while (users.next()) {
                int roles = users.getInt("role");
                dataTable[x][0] = users.getString("nama");
                dataTable[x][1] = users.getString("username");
                dataTable[x][2] = roles == 0 ? "Kepala" : "Pegawai";
                x++;
            }
            String[] header = {"Nama","Username","Role"};
            tabelUserData.setModel(new DefaultTableModel(dataTable, header));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void clear_field_users(){
        txtNama.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
    }
    
    private void data_jenis_kendaraan(){
        try {
            cmbJenisKendaraan.removeAllItems(); // Delete semua
            RsKonfigurasi = stm.executeQuery("select * from config where name = 'jenis_kendaraan'");
            while (RsKonfigurasi.next()) {
                cmbJenisKendaraan.addItem(RsKonfigurasi.getString("value").trim()); // Input ke cmb box
            }
            System.out.println(cmbJenisKendaraan);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void data_kapasitas(){
        try {
            RsKonfigurasi = stm.executeQuery("select * from config where name = 'kapasitas'");
            while (RsKonfigurasi.next()) {
                txtKapasitas.setText(RsKonfigurasi.getString("value"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKapasitas = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmbJenisKendaraan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtJenisKendaraan = new javax.swing.JTextField();
        btnTambahKendaraan = new javax.swing.JButton();
        btnEditKendaraan = new javax.swing.JButton();
        btnDeleteKendaraan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        btnUpdateUser = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelUserData = new javax.swing.JTable();
        btnSimpanKapasitas = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Konfigurasi Parkir");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kapasitas");

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jenis Kendaraan");

        cmbJenisKendaraan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbJenisKendaraanFocusLost(evt);
            }
        });
        cmbJenisKendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbJenisKendaraanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbJenisKendaraanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbJenisKendaraanMouseReleased(evt);
            }
        });
        cmbJenisKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJenisKendaraanActionPerformed(evt);
            }
        });
        cmbJenisKendaraan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbJenisKendaraanKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Jenis");

        btnTambahKendaraan.setText("Tambah");
        btnTambahKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKendaraanActionPerformed(evt);
            }
        });
        btnTambahKendaraan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnTambahKendaraanKeyPressed(evt);
            }
        });

        btnEditKendaraan.setText("Ubah");
        btnEditKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditKendaraanActionPerformed(evt);
            }
        });

        btnDeleteKendaraan.setText("Hapus");
        btnDeleteKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteKendaraanActionPerformed(evt);
            }
        });
        btnDeleteKendaraan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDeleteKendaraanKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtJenisKendaraan)
                            .addComponent(cmbJenisKendaraan, 0, 214, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnTambahKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbJenisKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJenisKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jButton4.setText("Tambah");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnUpdateUser.setText("Ubah");
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        btnDeleteUser.setText("Hapus");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User Data");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Role");

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kepala", "Pegawai" }));

        tabelUserData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "Username", "Role"
            }
        ));
        tabelUserData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelUserDataMouseClicked(evt);
            }
        });
        tabelUserData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelUserDataKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabelUserData);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsername)
                            .addComponent(txtNama)
                            .addComponent(txtPassword)
                            .addComponent(cmbRole, 0, 190, Short.MAX_VALUE)))
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnSimpanKapasitas.setText("Simpan");
        btnSimpanKapasitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanKapasitasActionPerformed(evt);
            }
        });

        jButton8.setText("Keluar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSimpanKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahKendaraanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnTambahKendaraanKeyPressed
        
    }//GEN-LAST:event_btnTambahKendaraanKeyPressed

    private void btnDeleteKendaraanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDeleteKendaraanKeyPressed
        
    }//GEN-LAST:event_btnDeleteKendaraanKeyPressed

    private void btnTambahKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKendaraanActionPerformed
        String jnsKendaraan = txtJenisKendaraan.getText();
        try {
            stm.executeUpdate("INSERT into config (name,value) values('jenis_kendaraan','"+jnsKendaraan+"')");
            JOptionPane.showMessageDialog(null, "Sukses Input Jenis Kendaraan");
            data_jenis_kendaraan(); // Combox jenis kendaraan nya di update
            txtJenisKendaraan.setText(""); // di clear
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e); 
        }
    }//GEN-LAST:event_btnTambahKendaraanActionPerformed

    private void btnDeleteKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteKendaraanActionPerformed
        String jnsKendaraan = cmbJenisKendaraan.getSelectedItem().toString();
        try {
            stm.executeUpdate("DELETE FROM config WHERE name = 'jenis_kendaraan' and value = '"+ jnsKendaraan +"'");
            JOptionPane.showMessageDialog(null, "Sukses Hapus Jenis Kendaraan");
            data_jenis_kendaraan();
            txtJenisKendaraan.setText("");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e); 
        }
    }//GEN-LAST:event_btnDeleteKendaraanActionPerformed

    private void cmbJenisKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJenisKendaraanActionPerformed
        JComboBox vJenisKendaraan = (javax.swing.JComboBox)evt.getSource();
        if (cmbJenisKendaraan.getSelectedItem() != null) {
           txtJenisKendaraan.setText(cmbJenisKendaraan.getSelectedItem().toString()); 
        }
        
    }//GEN-LAST:event_cmbJenisKendaraanActionPerformed

    private void btnEditKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditKendaraanActionPerformed
        String jnsKendaraan = txtJenisKendaraan.getText();
        String cmbjnsKendaraan = cmbJenisKendaraan.getSelectedItem().toString();
        try {
            stm.executeUpdate("UPDATE config SET value = '"+ jnsKendaraan +"'" +" WHERE name = 'jenis_kendaraan' and value = '"+ cmbjnsKendaraan +"'" );
            JOptionPane.showMessageDialog(null, "Sukses Update Jenis Kendaraan");
            data_jenis_kendaraan();
            txtJenisKendaraan.setText("");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e); 
        }
    }//GEN-LAST:event_btnEditKendaraanActionPerformed

    private void cmbJenisKendaraanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbJenisKendaraanKeyPressed
        
    }//GEN-LAST:event_cmbJenisKendaraanKeyPressed

    private void cmbJenisKendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbJenisKendaraanMouseClicked
        
    }//GEN-LAST:event_cmbJenisKendaraanMouseClicked

    private void cmbJenisKendaraanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbJenisKendaraanMouseReleased
     
    }//GEN-LAST:event_cmbJenisKendaraanMouseReleased

    private void cmbJenisKendaraanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbJenisKendaraanMousePressed
        
    }//GEN-LAST:event_cmbJenisKendaraanMousePressed

    private void cmbJenisKendaraanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbJenisKendaraanFocusLost
        JComboBox vJenisKendaraan = (javax.swing.JComboBox)evt.getSource();
        txtJenisKendaraan.setText(vJenisKendaraan.getSelectedItem().toString());
    }//GEN-LAST:event_cmbJenisKendaraanFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String nama = txtNama.getText().toString();
        String username = txtUsername.getText().toString();
        String password = txtPassword.getText().toString();
        int role = cmbRole.getSelectedIndex();
        try {
            stm.executeUpdate("INSERT into users (nama,username,password,role) values('"+nama.toUpperCase()+"','"+username+"',md5('"+password+"'),"+role+")");
            JOptionPane.showMessageDialog(null, "Sukses Input Users");
            clear_field_users();
            baca_data_users();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e); 
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tabelUserDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelUserDataKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelUserDataKeyPressed

    private void tabelUserDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelUserDataMouseClicked
        set_field_users();
    }//GEN-LAST:event_tabelUserDataMouseClicked

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        String nama = txtNama.getText().toString();
        String username = txtUsername.getText().toString();
        String password = txtPassword.getText().toString();
        int role = cmbRole.getSelectedIndex();
        try {
            stm.executeUpdate("UPDATE users SET nama = '"+nama.toUpperCase()+"',username = '"+username+"',"
                    + "password = md5('"+password+"'), role = "+role+" WHERE username = '"+tempUsername+"'");
            JOptionPane.showMessageDialog(null, "Sukses Update Users");
            clear_field_users();
            baca_data_users();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e); 
        }
    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        try {
            stm.executeUpdate("DELETE FROM users WHERE  username = '"+ tempUsername +"'");
            JOptionPane.showMessageDialog(null, "Sukses Hapus Data User");
            clear_field_users();
            baca_data_users();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e); 
        }
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void btnSimpanKapasitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanKapasitasActionPerformed
        
        try {
            stm.executeUpdate("UPDATE config SET value = '"+txtKapasitas.getText()+"' WHERE name = 'kapasitas'");
            JOptionPane.showMessageDialog(null, "Sukses Update Kapasitas");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e); 
        }
    }//GEN-LAST:event_btnSimpanKapasitasActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed
    
    private void set_field_users(){
        int row=tabelUserData.getSelectedRow();
        txtNama.setText((String)tabelUserData.getValueAt(row,0));
        txtUsername.setText((String)tabelUserData.getValueAt(row,1));
        cmbRole.setSelectedItem((String)tabelUserData.getValueAt(row,2));
        
        tempUsername = (String)tabelUserData.getValueAt(row,1);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Konfigurasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Konfigurasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Konfigurasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Konfigurasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Konfigurasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteKendaraan;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnEditKendaraan;
    private javax.swing.JButton btnSimpanKapasitas;
    private javax.swing.JButton btnTambahKendaraan;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JComboBox<String> cmbJenisKendaraan;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelUserData;
    private javax.swing.JTextField txtJenisKendaraan;
    private javax.swing.JTextField txtKapasitas;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
